from django.db import models

class Data_Model(models.Model):
    organization_name = models.CharField(max_length=100, default='NA')
    tax_id = models.CharField(max_length=20, default='NA')
    domain_name = models.CharField(max_length=200, default='NA')
    other_domains = models.CharField(max_length=200, default='NA')
    country = models.CharField(max_length=50, default='NA')
    organization_phone_number = models.CharField(max_length=20, default='NA')
    organization_fax = models.CharField(max_length=20, default='NA')
    dm_first_name = models.CharField(max_length=50, default='NA')
    dm_last_name = models.CharField(max_length=50, default='NA')
    title = models.CharField(max_length=100, default='NA')
    dm_mobile_number = models.CharField(max_length=20, default='NA')
    dm_email = models.CharField(max_length=100, default='NA')
    dm_fax_number = models.CharField(max_length=20, default='NA')
    dm_did_phone_number = models.CharField(max_length=20, default='NA')
    notes = models.CharField(max_length=500, default='NA')
    other = models.CharField(max_length=500, default='NA')
    status = models.CharField(max_length=10, default='NA')
    sales_agent_company = models.CharField(max_length=100, default='NA')
    sales_agent = models.CharField(max_length=50, default='NA')
    billing_email = models.CharField(max_length=100, default='NA')
    staff_support_users = models.CharField(max_length=500, default='NA')
    bill_dispute_email = models.CharField(max_length=100, default='NA')
    end_user_admins = models.CharField(max_length=500, default='NA')
    bill_escalate_email = models.CharField(max_length=100, default='NA')
    end_users = models.CharField(max_length=500, default='NA')
    end_user_billings = models.CharField(max_length=500, default='NA')
    
